<a href="https://colab.research.google.com/github/galahad20/assignment_Data_Manipulation/blob/main/ASSIGNMENT_TEMP_DE14_DAY11_DIMAS_ABIAN_IHSAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Data Manipulation
by `Dimas Abian Ihsan`

**Dibimbing - Batch 14 | DE**

**Riwayat Implementasi Github Collaboration Flow
 :** https://github.com/galahad20/assignment_Data_Manipulation

Objectives
- Student mampu melakukan filter dan select data menggunakan pandas
- Student mampu melakukan group by dan agregasi data
- Student mampu melakukan join/merge antar tabel
- Student mampu melakukan operasi dataframe
- Student mampu melakukan transformasi dan feature engineering

## Persiapan

### Import Library

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

%matplotlib inline
print('Libraries Loaded!')

Libraries Loaded!

### Import Dataset

In [3]:
#import data customers
cust_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/customers.csv'
cust = pd.read_csv(cust_path)
cust.head()

,customer_id,customer_name,email,city,province,registration_date,membership_tier
0,C001,Andi Wijaya,andi.wijaya@email.com,Jakarta,DKI Jakarta,2024-01-15,Gold
1,C002,Budi Santoso,budi.santoso@email.com,Bandung,Jawa Barat,2024-02-20,Silver
2,C003,Citra Dewi,citra.dewi@email.com,Surabaya,Jawa Timur,2024-03-10,Gold
3,C004,Dian Pratama,dian.pratama@email.com,Medan,Sumatera Utara,2024-04-05,Bronze
4,C005,Eka Putri,eka.putri@email.com,Jakarta,DKI Jakarta,2024-05-12,Platinum

In [4]:
#import data orders
order_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/orders.csv'
order = pd.read_csv(order_path)
order.head()

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
2,ORD0003,C003,Citra Dewi,2025-01-07,P003,Sepatu Nike,Fashion,1,1500000,0,1500000,Surabaya,E-Wallet,Delivered
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered
4,ORD0005,C004,Dian Pratama,2025-01-09,P005,Tas Ransel,Fashion,2,450000,5,855000,Medan,COD,Delivered

In [5]:
#import data products
prod_path = '/content/drive/MyDrive/dibimbing/assignment/dataset-day11/products.csv'
prod = pd.read_csv(prod_path)
prod.head()

,product_id,product_name,category,brand,unit_cost,unit_price,stock_qty
0,P001,Laptop ASUS,Electronics,ASUS,10000000,12500000,50
1,P002,Smartphone Samsung,Electronics,Samsung,6800000,8500000,100
2,P003,Sepatu Nike,Fashion,Nike,1200000,1500000,200
3,P004,Mouse Logitech,Electronics,Logitech,280000,350000,500
4,P005,Tas Ransel,Fashion,Local,360000,450000,150

### Cek info kolom, null, dan duplicate

In [6]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        20 non-null     object
 1   customer_name      20 non-null     object
 2   email              20 non-null     object
 3   city               20 non-null     object
 4   province           20 non-null     object
 5   registration_date  20 non-null     object
 6   membership_tier    20 non-null     object
dtypes: object(7)
memory usage: 1.2+ KB

In [7]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     object
 1   customer_id     50 non-null     object
 2   customer_name   50 non-null     object
 3   order_date      50 non-null     object
 4   product_id      50 non-null     object
 5   product_name    50 non-null     object
 6   category        50 non-null     object
 7   quantity        50 non-null     int64
 8   unit_price      50 non-null     int64
 9   discount_pct    50 non-null     int64
 10  total_amount    50 non-null     int64
 11  city            50 non-null     object
 12  payment_method  50 non-null     object
 13  order_status    50 non-null     object
dtypes: int64(4), object(10)
memory usage: 5.6+ KB

In [8]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    15 non-null     object
 1   product_name  15 non-null     object
 2   category      15 non-null     object
 3   brand         15 non-null     object
 4   unit_cost     15 non-null     int64
 5   unit_price    15 non-null     int64
 6   stock_qty     15 non-null     int64
dtypes: int64(3), object(4)
memory usage: 972.0+ bytes

In [9]:
#cek null dan duplicate
list_df = [prod, cust, order]
for df in list_df:
  print(df.isna().sum())

print(f"--------------------")
for df in list_df:
  print(df.duplicated().sum())

product_id      0
product_name    0
category        0
brand           0
unit_cost       0
unit_price      0
stock_qty       0
dtype: int64
customer_id          0
customer_name        0
email                0
city                 0
province             0
registration_date    0
membership_tier      0
dtype: int64
order_id          0
customer_id       0
customer_name     0
order_date        0
product_id        0
product_name      0
category          0
quantity          0
unit_price        0
discount_pct      0
total_amount      0
city              0
payment_method    0
order_status      0
dtype: int64
--------------------
0
0
0

## Filter and select

### Filter orders yang memiliki category = “Electronics”

In [10]:
order[order['category']== 'Electronics']

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered
5,ORD0006,C005,Eka Putri,2025-01-10,P006,Headphone Sony,Electronics,1,2500000,15,2125000,Jakarta,Credit Card,Delivered
7,ORD0008,C006,Fajar Nugroho,2025-01-12,P008,Keyboard Mechanical,Electronics,1,1200000,10,1080000,Yogyakarta,E-Wallet,Delivered
10,ORD0011,C008,Hendra Kusuma,2025-01-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Makassar,Bank Transfer,Delivered
11,ORD0012,C009,Indah Permata,2025-01-16,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Denpasar,E-Wallet,Delivered
16,ORD0017,C011,Kartika Sari,2025-01-21,P004,Mouse Logitech,Electronics,2,350000,5,665000,Batam,COD,Delivered
18,ORD0019,C002,Budi Santoso,2025-01-23,P006,Headphone Sony,Electronics,1,2500000,10,2250000,Bandung,Bank Transfer,Delivered
20,ORD0021,C014,Nanda Putra,2025-01-25,P008,Keyboard Mechanical,Electronics,1,1200000,0,1200000,Banjarmasin,COD,Delivered
25,ORD0026,C007,Gita Sari,2025-01-30,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Semarang,Credit Card,Delivered
27,ORD0028,C008,Hendra Kusuma,2025-02-01,P002,Smartphone Samsung,Electronics,1,8500000,0,8500000,Makassar,E-Wallet,Delivered
31,ORD0032,C010,Joko Widodo,2025-02-05,P004,Mouse Logitech,Electronics,4,350000,10,1260000,Palembang,E-Wallet,Delivered
34,ORD0035,C011,Kartika Sari,2025-02-08,P006,Headphone Sony,Electronics,1,2500000,10,2250000,Batam,Bank Transfer,Delivered
37,ORD0038,C005,Eka Putri,2025-02-11,P008,Keyboard Mechanical,Electronics,2,1200000,10,2160000,Jakarta,Credit Card,Delivered
41,ORD0042,C006,Fajar Nugroho,2025-02-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Yogyakarta,Credit Card,Delivered
43,ORD0044,C003,Citra Dewi,2025-02-17,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Surabaya,E-Wallet,Delivered
46,ORD0047,C017,Qori Amalia,2025-02-20,P004,Mouse Logitech,Electronics,1,350000,0,350000,Cirebon,Bank Transfer,Delivered

### Filter orders dengan total_amount > 5000000

In [11]:
order[order['total_amount'] > 5000000]

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered
10,ORD0011,C008,Hendra Kusuma,2025-01-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Makassar,Bank Transfer,Delivered
11,ORD0012,C009,Indah Permata,2025-01-16,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Denpasar,E-Wallet,Delivered
25,ORD0026,C007,Gita Sari,2025-01-30,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Semarang,Credit Card,Delivered
27,ORD0028,C008,Hendra Kusuma,2025-02-01,P002,Smartphone Samsung,Electronics,1,8500000,0,8500000,Makassar,E-Wallet,Delivered
41,ORD0042,C006,Fajar Nugroho,2025-02-15,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Yogyakarta,Credit Card,Delivered
43,ORD0044,C003,Citra Dewi,2025-02-17,P002,Smartphone Samsung,Electronics,1,8500000,5,8075000,Surabaya,E-Wallet,Delivered

### Select hanya kolom order_id, customer_name, product_name, total_amount

In [12]:
order[['order_id', 'customer_name', 'product_name', 'total_amount']]

   order_id   customer_name         product_name  total_amount
0   ORD0001     Andi Wijaya          Laptop ASUS      11250000
1   ORD0002    Budi Santoso   Smartphone Samsung      16150000
2   ORD0003      Citra Dewi          Sepatu Nike       1500000
3   ORD0004     Andi Wijaya       Mouse Logitech        945000
4   ORD0005    Dian Pratama           Tas Ransel        855000
5   ORD0006       Eka Putri       Headphone Sony       2125000
6   ORD0007    Budi Santoso           Dress Zara        850000
7   ORD0008   Fajar Nugroho  Keyboard Mechanical       1080000
8   ORD0009       Gita Sari         Celana Jeans        760000
9   ORD0010      Citra Dewi           Jam Tangan       1200000
10  ORD0011   Hendra Kusuma          Laptop ASUS      11250000
11  ORD0012   Indah Permata   Smartphone Samsung       8075000
12  ORD0013     Joko Widodo          Sepatu Nike       2700000
13  ORD0014     Andi Wijaya         Skincare Set        550000
14  ORD0015    Dian Pratama          Parfum Dior       1870000
15  ORD0016       Eka Putri     Kacamata Ray-Ban       3150000
16  ORD0017    Kartika Sari       Mouse Logitech        665000
17  ORD0018    Lukman Hakim           Tas Ransel        450000
18  ORD0019    Budi Santoso       Headphone Sony       2250000
19  ORD0020      Maya Putri           Dress Zara       1615000
20  ORD0021     Nanda Putra  Keyboard Mechanical       1200000
21  ORD0022      Citra Dewi          Lipstik MAC       1215000
22  ORD0023       Oscar Tan         Celana Jeans        380000
23  ORD0024   Fajar Nugroho           Jam Tangan       1020000
24  ORD0025       Putri Ayu         Dompet Kulit       1300000
25  ORD0026       Gita Sari          Laptop ASUS      11250000
26  ORD0027     Qori Amalia         Skincare Set       1045000
27  ORD0028   Hendra Kusuma   Smartphone Samsung       8500000
28  ORD0029    Rizky Fauzan          Parfum Dior       1980000
29  ORD0030   Indah Permata          Sepatu Nike       1425000
30  ORD0031      Sinta Dewi     Kacamata Ray-Ban       2975000
31  ORD0032     Joko Widodo       Mouse Logitech       1260000
32  ORD0033  Taufik Hidayat          Lipstik MAC        900000
33  ORD0034     Andi Wijaya           Tas Ransel        427500
34  ORD0035    Kartika Sari       Headphone Sony       2250000
35  ORD0036    Dian Pratama         Dompet Kulit        650000
36  ORD0037    Lukman Hakim           Dress Zara        807500
37  ORD0038       Eka Putri  Keyboard Mechanical       2160000
38  ORD0039      Maya Putri         Celana Jeans       1020000
39  ORD0040    Budi Santoso           Jam Tangan       1200000
40  ORD0041     Nanda Putra         Skincare Set        522500
41  ORD0042   Fajar Nugroho          Laptop ASUS      11250000
42  ORD0043       Oscar Tan          Parfum Dior       2200000
43  ORD0044      Citra Dewi   Smartphone Samsung       8075000
44  ORD0045       Putri Ayu     Kacamata Ray-Ban       3150000
45  ORD0046       Gita Sari          Sepatu Nike       2550000
46  ORD0047     Qori Amalia       Mouse Logitech        350000
47  ORD0048   Hendra Kusuma          Lipstik MAC       1710000
48  ORD0049    Rizky Fauzan           Tas Ransel        810000
49  ORD0050   Indah Permata         Dompet Kulit        650000

## Group By dan Agregasi

### Hitung total penjualan (total_amount) per category

In [13]:
order.groupby('category')['total_amount'].sum()

category
Accessories     15295000
Beauty          11992500
Electronics    100085000
Fashion         16150000
Name: total_amount, dtype: int64

### Hitung jumlah order dan rata-rata total_amount per city

In [14]:
order.groupby('city').agg({
    'order_id' : 'count',
    'total_amount' : 'mean'
}).rename(columns={
    'order_id' : 'jumlah_order',
    'total_amount' : 'rata_rata_total_amount'
})

             jumlah_order  rata_rata_total_amount
city
Bandung                 4            5.112500e+06
Banjarmasin             2            8.612500e+05
Batam                   2            1.457500e+06
Cirebon                 2            6.975000e+05
Denpasar                3            3.383333e+06
Jakarta                 7            2.943929e+06
Jambi                   1            9.000000e+05
Makassar                3            7.153333e+06
Malang                  2            2.225000e+06
Manado                  2            6.287500e+05
Medan                   3            1.125000e+06
Padang                  1            2.975000e+06
Palembang               2            1.980000e+06
Pekanbaru               2            1.395000e+06
Pontianak               2            1.317500e+06
Samarinda               2            1.290000e+06
Semarang                3            4.853333e+06
Surabaya                4            2.997500e+06
Yogyakarta              3            4.450000e+06

### Tentukan top 5 customer dengan total pembelian tertinggi

In [18]:
order.groupby('customer_name').agg({
    'total_amount' : 'sum'
}).sort_values('total_amount', ascending=False).head()

               total_amount
customer_name
Hendra Kusuma      21460000
Budi Santoso       20450000
Gita Sari          14560000
Fajar Nugroho      13350000
Andi Wijaya        13172500

## Join/Merge Data

### Gabungkan tabel orders dengan products berdasarkan product_id

In [21]:
order_with_prod = order.merge(prod, on='product_id', how='inner')
order_with_prod.head()

,order_id,customer_id,customer_name,order_date,product_id,product_name_x,category_x,quantity,unit_price_x,discount_pct,total_amount,city,payment_method,order_status,product_name_y,category_y,brand,unit_cost,unit_price_y,stock_qty
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered,Laptop ASUS,Electronics,ASUS,10000000,12500000,50
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered,Smartphone Samsung,Electronics,Samsung,6800000,8500000,100
2,ORD0003,C003,Citra Dewi,2025-01-07,P003,Sepatu Nike,Fashion,1,1500000,0,1500000,Surabaya,E-Wallet,Delivered,Sepatu Nike,Fashion,Nike,1200000,1500000,200
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered,Mouse Logitech,Electronics,Logitech,280000,350000,500
4,ORD0005,C004,Dian Pratama,2025-01-09,P005,Tas Ransel,Fashion,2,450000,5,855000,Medan,COD,Delivered,Tas Ransel,Fashion,Local,360000,450000,150

### Gabungkan tabel orders dengan customers berdasarkan customer_id

In [22]:
order_with_cust = order.merge(cust, on='customer_id', how='inner')
order_with_cust.head()

,order_id,customer_id,customer_name_x,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city_x,payment_method,order_status,customer_name_y,email,city_y,province,registration_date,membership_tier
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered,Andi Wijaya,andi.wijaya@email.com,Jakarta,DKI Jakarta,2024-01-15,Gold
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered,Budi Santoso,budi.santoso@email.com,Bandung,Jawa Barat,2024-02-20,Silver
2,ORD0003,C003,Citra Dewi,2025-01-07,P003,Sepatu Nike,Fashion,1,1500000,0,1500000,Surabaya,E-Wallet,Delivered,Citra Dewi,citra.dewi@email.com,Surabaya,Jawa Timur,2024-03-10,Gold
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered,Andi Wijaya,andi.wijaya@email.com,Jakarta,DKI Jakarta,2024-01-15,Gold
4,ORD0005,C004,Dian Pratama,2025-01-09,P005,Tas Ransel,Fashion,2,450000,5,855000,Medan,COD,Delivered,Dian Pratama,dian.pratama@email.com,Medan,Sumatera Utara,2024-04-05,Bronze

### Hitung profit per order (gunakan unit_price dan unit_cost dari products)

Disini saya simpan nilai profit ke dalam kolom baru agar bisa digunakan lagi nantinya

In [51]:
#perhitungan profit
order_with_prod['profit'] = ((order_with_prod['unit_price_y'] * order_with_prod['quantity']) * (1 - order_with_prod['discount_pct']/100))  - (order_with_prod['unit_cost'] * order_with_prod['quantity'])

#filtering with group by
order_with_prod.groupby('order_id')['profit'].sum().reset_index()

   order_id     profit
0   ORD0001  1250000.0
1   ORD0002  2550000.0
2   ORD0003   300000.0
3   ORD0004   105000.0
4   ORD0005   135000.0
5   ORD0006   125000.0
6   ORD0007   170000.0
7   ORD0008   120000.0
8   ORD0009   120000.0
9   ORD0010   240000.0
10  ORD0011  1250000.0
11  ORD0012  1275000.0
12  ORD0013   300000.0
13  ORD0014   110000.0
14  ORD0015   110000.0
15  ORD0016   350000.0
16  ORD0017   105000.0
17  ORD0018    90000.0
18  ORD0019   250000.0
19  ORD0020   255000.0
20  ORD0021   240000.0
21  ORD0022   135000.0
22  ORD0023    60000.0
23  ORD0024    60000.0
24  ORD0025   260000.0
25  ORD0026  1250000.0
26  ORD0027   165000.0
27  ORD0028  1700000.0
28  ORD0029   220000.0
29  ORD0030   225000.0
30  ORD0031   175000.0
31  ORD0032   140000.0
32  ORD0033   180000.0
33  ORD0034    67500.0
34  ORD0035   250000.0
35  ORD0036   130000.0
36  ORD0037   127500.0
37  ORD0038   240000.0
38  ORD0039    60000.0
39  ORD0040   240000.0
40  ORD0041    82500.0
41  ORD0042  1250000.0
42  ORD0043   440000.0
43  ORD0044  1275000.0
44  ORD0045   350000.0
45  ORD0046   150000.0
46  ORD0047    70000.0
47  ORD0048   270000.0
48  ORD0049    90000.0
49  ORD0050   130000.0

In [54]:
#detail order_per_profit
order_with_prod.groupby('order_id').agg({
    'product_name_y' : 'first',
    'total_amount' : 'first',
    'discount_pct' : 'first',
    'quantity' : 'sum',
    'unit_price_y' : 'first',
    'unit_cost' : 'first',
    'profit' : 'sum'
}).reset_index().head()

,order_id,product_name_y,total_amount,discount_pct,quantity,unit_price_y,unit_cost,profit
0,ORD0001,Laptop ASUS,11250000,10,1,12500000,10000000,1250000.0
1,ORD0002,Smartphone Samsung,16150000,5,2,8500000,6800000,2550000.0
2,ORD0003,Sepatu Nike,1500000,0,1,1500000,1200000,300000.0
3,ORD0004,Mouse Logitech,945000,10,3,350000,280000,105000.0
4,ORD0005,Tas Ransel,855000,5,2,450000,360000,135000.0

## Datetime Operations

### Konversi kolom order_date ke tipe datetime

In [35]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     object
 1   customer_id     50 non-null     object
 2   customer_name   50 non-null     object
 3   order_date      50 non-null     object
 4   product_id      50 non-null     object
 5   product_name    50 non-null     object
 6   category        50 non-null     object
 7   quantity        50 non-null     int64
 8   unit_price      50 non-null     int64
 9   discount_pct    50 non-null     int64
 10  total_amount    50 non-null     int64
 11  city            50 non-null     object
 12  payment_method  50 non-null     object
 13  order_status    50 non-null     object
dtypes: int64(4), object(10)
memory usage: 5.6+ KB

In [36]:
order['order_date'] = pd.to_datetime(order['order_date'])
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     object
 1   customer_id     50 non-null     object
 2   customer_name   50 non-null     object
 3   order_date      50 non-null     datetime64[ns]
 4   product_id      50 non-null     object
 5   product_name    50 non-null     object
 6   category        50 non-null     object
 7   quantity        50 non-null     int64
 8   unit_price      50 non-null     int64
 9   discount_pct    50 non-null     int64
 10  total_amount    50 non-null     int64
 11  city            50 non-null     object
 12  payment_method  50 non-null     object
 13  order_status    50 non-null     object
dtypes: datetime64[ns](1), int64(4), object(9)
memory usage: 5.6+ KB

### Extract bulan dan hari dari order_date

In [39]:
order['month'] = order['order_date'].dt.month
order[['month']].head()

   month
0      1
1      1
2      1
3      1
4      1

### Hitung total penjualan per bulan

In [40]:
order.groupby('month')['total_amount'].sum()

month
1    86700000
2    56822500
Name: total_amount, dtype: int64

### Identifikasi hari dalam seminggu dengan penjualan tertinggi

Jujur soalnya agak ambigu banyak penafsiran berbeda seperti

- apakah identifikasi hari dalam seminggu dengan penjualan tertinggi dan itu diulang lagi untuk minggu lainnya dan ditampilkan per minggu

- Atau identifikasi hari dalam seminggu dengan penjualan tertinggi. Kemudian jumlahkan dengan hari yang sama di minggu lain sehingga dapat hasilnya dan kemudian bandingkan dengan hari lain dalam seminggu. Sehingg didapatkan total penjualan tertinggi itu pada hari A misalnya jika dibandingkan dengan total hari lainnya.

- Atau bahkan identifikasi seluruh hari dalam seminggu di dataset itu dan hanya tampilkan hari dengan penjualan tertingginya saja, meskipun hari itu biasanya tidak tinggi penjualannya di minggu lainnya namun selama masih penjualan tertinggi (misal tanggal kembar) itu yang ditampilkan.

Namun saya sampati dengan kesimpulan ke-2 bahwa identifikasi hari yang akumulasi atau tren keseluruhan dalam seminggu di tiap minggunya memilki total penjualan tertinggi.

In [56]:
#membuat kolom day dari order date
order['day'] = order['order_date'].dt.day_name()

In [57]:
order.head()

,order_id,customer_id,customer_name,order_date,product_id,product_name,category,quantity,unit_price,discount_pct,total_amount,city,payment_method,order_status,month,day
0,ORD0001,C001,Andi Wijaya,2025-01-05,P001,Laptop ASUS,Electronics,1,12500000,10,11250000,Jakarta,Credit Card,Delivered,1,Sunday
1,ORD0002,C002,Budi Santoso,2025-01-06,P002,Smartphone Samsung,Electronics,2,8500000,5,16150000,Bandung,Bank Transfer,Delivered,1,Monday
2,ORD0003,C003,Citra Dewi,2025-01-07,P003,Sepatu Nike,Fashion,1,1500000,0,1500000,Surabaya,E-Wallet,Delivered,1,Tuesday
3,ORD0004,C001,Andi Wijaya,2025-01-08,P004,Mouse Logitech,Electronics,3,350000,10,945000,Jakarta,Credit Card,Delivered,1,Wednesday
4,ORD0005,C004,Dian Pratama,2025-01-09,P005,Tas Ransel,Fashion,2,450000,5,855000,Medan,COD,Delivered,1,Thursday

In [62]:
#group by day dan sort by day dengan penjualan tertinggi
order.groupby('day')['total_amount'].sum().reset_index().sort_values(by='total_amount', ascending=False)

         day  total_amount
1     Monday      30747500
2   Saturday      25410000
4   Thursday      24880000
3     Sunday      20895000
6  Wednesday      18775000
5    Tuesday      12670000
0     Friday      10145000

Dari hasil di atas akan menampilkan tren yang mana dari data yang diberikan, monday menjadi hari dengan total penjualan tertinggi.

## Feature Engineering
Buat segmentasi customer berdasarkan total spending (Low, Medium, High)
Buat kolom is_weekend berdasarkan order_date

### Buat kolom baru profit_margin = (unit_price - unit_cost) / unit_price * 100